services:
  kafka-broker-2:
    image: bitnami/kafka:3.9.0
    container_name: kafka-broker-2
    ports:
      - '9094:9092'
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-2:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-broker-1:9093,1@kafka-broker-2:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - ./kafka/conf/workaround.sh:/workaround.sh
      - kafka_data_broker_2:/bitnami/kafka
    entrypoint: ["/bin/bash", "/workaround.sh"]

volumes:
  kafka_data_broker_2:
